// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUPxRgHxorI_nM0RvEOli8cdvHP3AoJ4',
    appId: '1:575130445461:web:341a32e11b41fefd649d9c',
    messagingSenderId: '575130445461',
    projectId: 'classwork-06-5d606',
    authDomain: 'classwork-06-5d606.firebaseapp.com',
    storageBucket: 'classwork-06-5d606.firebasestorage.app',
    measurementId: 'G-2XGYBPPQDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd8MmZy9mXTYjMthKMaEExsijeCefZjOA',
    appId: '1:575130445461:android:2af380f8d3db3fab649d9c',
    messagingSenderId: '575130445461',
    projectId: 'classwork-06-5d606',
    storageBucket: 'classwork-06-5d606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2zeGz31zFvv9woOLjVoXdBTjyp6v3dI',
    appId: '1:575130445461:ios:1d6289fc0626fa7f649d9c',
    messagingSenderId: '575130445461',
    projectId: 'classwork-06-5d606',
    storageBucket: 'classwork-06-5d606.firebasestorage.app',
    iosBundleId: 'com.example.madCw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2zeGz31zFvv9woOLjVoXdBTjyp6v3dI',
    appId: '1:575130445461:ios:1d6289fc0626fa7f649d9c',
    messagingSenderId: '575130445461',
    projectId: 'classwork-06-5d606',
    storageBucket: 'classwork-06-5d606.firebasestorage.app',
    iosBundleId: 'com.example.madCw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvUPxRgHxorI_nM0RvEOli8cdvHP3AoJ4',
    appId: '1:575130445461:web:45a21466581b312b649d9c',
    messagingSenderId: '575130445461',
    projectId: 'classwork-06-5d606',
    authDomain: 'classwork-06-5d606.firebaseapp.com',
    storageBucket: 'classwork-06-5d606.firebasestorage.app',
    measurementId: 'G-T1Q1GBWRHM',
  );
}
